---
title: "{front | Fabi}"
baseURL: "http://frontfabi.com.br/"
theme: "zen"
languageCode: "pt"
defaultContentLanguage: "pt"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Fabi"
  url: "https://frontfabi.com.br/"
  avatar: "path/to/some-image.jpg"

outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS", "JSON"]

params:
  contact: "frontfabi@gmail.com"
  description: "Desenvolvedora, mentora e palestrante."
  dateformat: "02/01/2006"
  favicon: "icon-64.png"
  feedlinks: true
  footer: "Feito com [Hugo](https://gohugo.io/)."
  icon: "apple-touch-icon-180.png"
  image: "apple-touch-icon-180.png"
  imageMaxWidth: 400
  jquery: true
  mobileMenu: true
  poweredby: false
  search: false
  searchSize: 20
  sidebar: true
  submitted: true
  mainSections: ["posts"]
